assess/app/assess/models/comment.py
import inspect
from dataclasses import dataclass


@dataclass
class Comment:
    comment: str
    user_id: str
    date_created: str
    email_address: str
    full_name: str
    highest_role: str
    theme_id: str
    fund_short_name: str

    @classmethod
    def from_dict(cls, d: dict):
        # Filter unknown fields from JSON dictionary
        return cls(
            **{
                k: v
                for k, v in d.items()
                if k in inspect.signature(cls).parameters
            }
        )

    @property
    def from_lead_assessor(self):
        return (
            f"{self.fund_short_name}_{self.highest_role}"
            == f"{self.fund_short_name}_LEAD_ASSESSOR"
        )

    @property
    def from_assessor(self):
        return (
            f"{self.fund_short_name}_{self.highest_role}"
            == f"{self.fund_short_name}_ASSESSOR"
        )

    @property
    def from_any_assessor(self):
        return self.from_lead_assessor or self.from_assessor

assess/app/assess/models/score.py
import inspect
from dataclasses import dataclass
from datetime import datetime


@dataclass
class Score:
    id: str
    application_id: str
    sub_criteria_id: str
    score: str
    justification: str
    date_created: str
    user_id: str
    user_full_name: str
    user_email: str
    highest_role: str

    def __post_init__(self):
        self.date_created = datetime.fromisoformat(self.date_created).strftime(
            "%Y-%m-%d %X"
        )

    @classmethod
    def from_dict(cls, d: dict):
        # Filter unknown fields from JSON dictionary
        return cls(
            **{
                k: v
                for k, v in d.items()
                if k in inspect.signature(cls).parameters
            }
        )

assess/app/assess/models/theme.py
import inspect
from dataclasses import dataclass


@dataclass
class Theme:
    id: str
    name: str

    @classmethod
    def from_filtered_dict(cls, d: dict):
        # Filter unknown fields from JSON dictionary
        return cls(
            **{
                k: v
                for k, v in d.items()
                if k in inspect.signature(cls).parameters
            }
        )

assess/app/assess/forms/comments_form.py
from config import Config
from flask_wtf import FlaskForm
from wtforms import TextAreaField
from wtforms.validators import InputRequired
from wtforms.validators import length


class CommentsForm(FlaskForm):

    comment = TextAreaField(
        "Comment",
        validators=[
            length(max=Config.TEXT_AREA_INPUT_MAX_CHARACTERS),
            InputRequired(),
        ],
    )

assess/app/assess/routes.py
from datetime import datetime
from urllib.parse import quote_plus

from app.assess.auth.validation import check_access_application_id
from app.assess.auth.validation import check_access_fund_short_name
from app.assess.auth.validation import get_countries_from_roles
from app.assess.auth.validation import has_access_to_fund
from app.assess.auth.validation import has_devolved_authority_validation
from app.assess.data import *
from app.assess.data import get_application_json
from app.assess.data import get_application_overviews
from app.assess.data import get_assessments_stats
from app.assess.data import get_available_teams
from app.assess.data import get_flag
from app.assess.data import submit_score_and_justification
from app.assess.display_value_mappings import assessment_statuses
from app.assess.display_value_mappings import asset_types
from app.assess.display_value_mappings import funding_types
from app.assess.display_value_mappings import search_params_cof
from app.assess.display_value_mappings import search_params_nstf
from app.assess.forms.assessment_form import AssessmentCompleteForm
from app.assess.forms.comments_form import CommentsForm
from app.assess.forms.continue_application_form import ContinueApplicationForm
from app.assess.forms.flag_form import FlagApplicationForm
from app.assess.forms.mark_qa_complete_form import MarkQaCompleteForm
from app.assess.forms.rescore_form import RescoreForm
from app.assess.forms.resolve_flag_form import ResolveFlagForm
from app.assess.forms.scores_and_justifications import ScoreForm
from app.assess.helpers import determine_display_status
from app.assess.helpers import get_ttl_hash
from app.assess.helpers import is_flaggable
from app.assess.helpers import is_qa_complete
from app.assess.helpers import resolve_application
from app.assess.helpers import set_application_status_in_overview
from app.assess.models.flag_v2 import FlagTypeV2
from app.assess.models.fund_summary import create_fund_summaries
from app.assess.models.fund_summary import is_after_today
from app.assess.models.theme import Theme
from app.assess.models.ui import applicants_response
from app.assess.models.ui.assessor_task_list import AssessorTaskList
from app.assess.status import all_status_completed
from app.assess.status import update_ar_status_to_completed
from app.assess.views.filters import utc_to_bst
from config import Config
from flask import Blueprint
from flask import current_app
from flask import g
from flask import redirect
from flask import render_template
from flask import request
from flask import Response
from flask import url_for
from fsd_utils import extract_questions_and_answers
from fsd_utils import generate_text_of_application

assess_bp = Blueprint(
    "assess_bp",
    __name__,
    url_prefix=Config.ASSESSMENT_HUB_ROUTE,
    template_folder="templates",
)


def get_state_for_tasklist_banner(application_id) -> AssessorTaskList:
    assessor_task_list_metadata = get_assessor_task_list_state(application_id)
    fund = get_fund(assessor_task_list_metadata["fund_id"])
    round = get_round(
        assessor_task_list_metadata["fund_id"],
        assessor_task_list_metadata["round_id"],
    )
    assessor_task_list_metadata["fund_name"] = fund.name
    assessor_task_list_metadata["fund_short_name"] = fund.short_name
    assessor_task_list_metadata["round_short_name"] = round.short_name
    state = AssessorTaskList.from_json(assessor_task_list_metadata)
    return state


@assess_bp.route(
    "/application_id/<application_id>/sub_criteria_id/<sub_criteria_id>",
    methods=["POST", "GET"],
)
@check_access_application_id
def display_sub_criteria(
    application_id,
    sub_criteria_id,
):
    """
    Page showing sub criteria and themes for an application
    """
    current_app.logger.info(f"Processing GET to {request.path}.")
    sub_criteria = get_sub_criteria(application_id, sub_criteria_id)
    theme_id = request.args.get("theme_id", sub_criteria.themes[0].id)
    comment_form = CommentsForm()
    try:
        current_theme: Theme = next(
            iter(t for t in sub_criteria.themes if t.id == theme_id)
        )
    except StopIteration:
        current_app.logger.warn("Unknown theme ID requested: " + theme_id)
        abort(404)
    add_comment_argument = request.args.get("add_comment") == "1"
    if add_comment_argument and comment_form.validate_on_submit():
        comment = comment_form.comment.data
        submit_comment(
            comment=comment,
            application_id=application_id,
            sub_criteria_id=sub_criteria_id,
            user_id=g.account_id,
            theme_id=theme_id,
        )

        return redirect(
            url_for(
                "assess_bp.display_sub_criteria",
                application_id=application_id,
                sub_criteria_id=sub_criteria_id,
                theme_id=theme_id,
                _anchor="comments",
            )
        )

    state = get_state_for_tasklist_banner(application_id)
    flags_list = get_flags(application_id)

    comment_response = get_comments(
        application_id=application_id,
        sub_criteria_id=sub_criteria_id,
        theme_id=theme_id,
    )

    # TODO add test for this function in data_operations
    theme_matched_comments = (
        match_comment_to_theme(
            comment_response, sub_criteria.themes, state.fund_short_name
        )
        if comment_response
        else None
    )

    display_status = determine_display_status(
        sub_criteria.workflow_status, flags_list
    )
    common_template_config = {
        "sub_criteria": sub_criteria,
        "application_id": application_id,
        "comments": theme_matched_comments,
        "is_flaggable": is_flaggable(display_status),
        "display_comment_box": add_comment_argument,
        "comment_form": comment_form,
        "current_theme": current_theme,
        "display_status": display_status,
    }

    theme_answers_response = get_sub_criteria_theme_answers(
        application_id, theme_id
    )

    answers_meta = applicants_response.create_ui_components(
        theme_answers_response, application_id
    )

    return render_template(
        "sub_criteria.html",
        answers_meta=answers_meta,
        state=state,
        **common_template_config,
    )


@assess_bp.route(
    "/application_id/<application_id>/sub_criteria_id/<sub_criteria_id>/score",
    methods=["POST", "GET"],
)
@check_access_application_id(roles_required=["LEAD_ASSESSOR", "ASSESSOR"])
def score(
    application_id,
    sub_criteria_id,
):
    sub_criteria: SubCriteria = get_sub_criteria(
        application_id, sub_criteria_id
    )

    if not sub_criteria.is_scored:
        abort(404)

    state = get_state_for_tasklist_banner(application_id)

    flags_list = get_flags(application_id)

    comment_response = get_comments(
        application_id=application_id,
        sub_criteria_id=sub_criteria_id,
        theme_id=None,
    )

    theme_matched_comments = (
        match_comment_to_theme(
            comment_response, sub_criteria.themes, state.fund_short_name
        )
        if comment_response
        else None
    )

    display_status = determine_display_status(
        sub_criteria.workflow_status, flags_list
    )
    score_form = ScoreForm()
    rescore_form = RescoreForm()
    is_rescore = rescore_form.validate_on_submit()
    if not is_rescore and request.method == "POST":
        if score_form.validate_on_submit():
            current_app.logger.info(f"Processing POST to {request.path}.")
            score = int(score_form.score.data)
            user_id = g.account_id
            justification = score_form.justification.data
            submit_score_and_justification(
                score=score,
                justification=justification,
                application_id=application_id,
                user_id=user_id,
                sub_criteria_id=sub_criteria_id,
            )
        else:
            is_rescore = True

    # call to assessment store to get latest score
    score_list = get_score_and_justification(
        application_id, sub_criteria_id, score_history=True
    )
    # TODO add test for this function in data_operations
    scores_with_account_details = match_score_to_user_account(
        score_list, state.fund_short_name
    )
    latest_score = (
        scores_with_account_details.pop(0)
        if (score_list is not None and len(scores_with_account_details) > 0)
        else None
    )
    # TODO make COF_score_list extendable to other funds
    scoring_list = [
        (5, "Strong"),
        (4, "Good"),
        (3, "Satisfactory"),
        (2, "Partial"),
        (1, "Poor"),
    ]
    return render_template(
        "score.html",
        application_id=application_id,
        score_list=scores_with_account_details or None,
        latest_score=latest_score,
        scoring_list=scoring_list,
        score_form=score_form,
        rescore_form=rescore_form,
        is_rescore=is_rescore,
        sub_criteria=sub_criteria,
        state=state,
        comments=theme_matched_comments,
        display_status=display_status,
        is_flaggable=is_flaggable(display_status),
    )


@assess_bp.route(
    "/flag/<application_id>",
    methods=["GET", "POST"],
)
@check_access_application_id(roles_required=["ASSESSOR"])
def flag(application_id):

    # Get assessor tasks list
    state = get_state_for_tasklist_banner(application_id)
    choices = [
        (item["sub_section_id"], item["sub_section_name"])
        for item in state.get_sub_sections_metadata()
    ]

    teams_available = get_available_teams(
        state.fund_id,
        state.round_id,
    )

    form = FlagApplicationForm(
        section_choices=choices,
        team_choices=[team["value"] for team in teams_available],
    )

    if request.method == "POST" and form.validate_on_submit():
        submit_flag(
            application_id,
            FlagTypeV2.RAISED.name,
            g.account_id,

assess/app/assess/templates/macros/assessment_flag.html
{% from "macros/flag_history.html" import display_flagged_sections %}

{% macro assessment_flagged(state, flag, user_info, application_id) %}
    <div class="assessment-alert assessment-alert--flagged" role="alert">
        <h1 class="assessment-alert__heading govuk-heading-l">
            {{ ("Flagged for "+ flag.latest_allocation if flag.latest_allocation else "Flagged") | title }}
        </h1>
        <h2>Reason</h2>
        <p>{{ flag.justification }}</p>
        <h2>Section(s) flagged</h2>
        {{ display_flagged_sections(state, application_id, flag.sections_to_flag) }}
        {# TODO: Notification is hardcoded. Change it once notification is implemented #}
        <h2>Notification sent</h2>
        <p>No</p><br>
        <p class="govuk-body-s">{{ user_info["full_name"] }} ({{ user_info["highest_role"] | all_caps_to_human }}) {{ user_info["email_address"] }}</p>
        <p class="govuk-body-s">{{ flag.date_created | utc_to_bst }}</p>
        {# TODO: Resolve flag will be removed #}
        {% if g.access_controller.is_lead_assessor %}
            <p class="govuk-body"><a class="govuk-link govuk-link--no-visited-state" href="{{ url_for('assess_bp.resolve_flag',application_id=application_id)}}?flag_id={{ flag.id }}">Resolve flag</a></p>
        {% endif %}
    </div>
{% endmacro %}

{% macro assessment_stopped(flag, user_info, application_id) %}
    <div class="assessment-alert assessment-alert--stopped" role="alert">
        <h1 class="assessment-alert__heading govuk-heading-l">Assessment {{ flag.latest_status.name | title }}</h1>
        <h2 class="govuk-heading-m">Reason</h2>
        <p class="govuk-body">{{ flag.justification }}</p>
        <p class="govuk-body-s">{{ user_info["full_name"] }} ({{ user_info["highest_role"] | all_caps_to_human }}) {{ user_info["email_address"] }}</p>
        <p class="govuk-body-s">{{ flag.date_created | utc_to_bst }}</p>
        {% if g.access_controller.is_lead_assessor %}
            <p class="govuk-body"><a class="govuk-link govuk-link--no-visited-state" href="{{ url_for('assess_bp.continue_assessment',application_id=application_id)}}?flag_id={{ flag.id }}">Remove flag and continue assessment</a></p>
        {% endif %}
    </div>
{% endmacro %}

assess/app/assess/templates/macros/comments.html
{% macro comment(comments) %}
<div class="govuk-!-margin-top-7" id="comments">
    <h2 class="govuk-heading-m govuk-!-margin-bottom-2">Comments</h2>
    <div id="more-detail-hint" class="govuk-hint">
      <p class="govuk-hint govuk-!-margin-top-0">Summarise any thoughts you have on the information provided.</p>
      <p class="govuk-hint govuk-!-margin-top-0">You cannot edit or delete your comment once you have saved it.</p>
    </div>
    {% if comments == None %}
    <div class="govuk-body govuk-!-margin-top-6">
        No comments have been left yet.
        </div>
    {% else %}
    {% for comment_list in comments.values() %}
        {% for comment in comment_list %}
        {% if not g.access_controller.has_any_assessor_role and comment.from_any_assessor %}
            <div class="comment-group">
             <p class="govuk-body">Permission required to see comment.</p>
            </div>
        {% else %}
            <div class="comment-group">
                <p class="govuk-body">{{ comment.comment }}</p>
                <p class="govuk-body-s">{{ comment.full_name }} ({{ comment.highest_role|all_caps_to_human }}) {{ comment.email_address }}</p>
                <p class="govuk-body-s">{{ comment.date_created|utc_to_bst }}</p>
            </div>
        {% endif %}
        {% endfor %}
    {% endfor %}
    {% endif %}
</div>
{% endmacro %}

assess/app/assess/templates/macros/comments_box.html
{%- from 'govuk_frontend_jinja/components/textarea/macro.html' import govukTextarea -%}
{%- from "govuk_frontend_jinja/components/button/macro.html" import govukButton -%}

{% macro comment_box(comment_form) %}

<form method="post">
<div class="govuk-grid-row">
    {{ comment_form.csrf_token }}
    <div class="govuk-grid-column-full">
    {{ govukTextarea({
    "name": comment_form.comment.id,
    "id": comment_form.comment.id,
    "rows": 8,
    "label": {
      "text": "Add a comment",
      "classes": "govuk-label--m",
      isPageHeading: true
    },
    "errorMessage": {
      "text": comment_form.comment.errors.0
  } if comment_form.comment.errors
  }) }}

  {{ govukButton({
    "text": "Save comment",
    "type": "submit",
    "classes": "primary-button govuk-!-margin-bottom-9"
  }) }}

    </div>
</div>
</form>

{% endmacro %}

assess/app/assess/templates/macros/criteria_element.html
{%- from "govuk_frontend_jinja/components/table/macro.html" import govukTable -%}
{% macro criteria_element(criteria, name_classes, application_id) %}

    {% set rows = [] %}
    {% for sub_criteria in criteria.sub_criterias %}
        {% set _ = rows.append([
            {
                "html": '<a class="govuk-link" data-qa="sub_criteria_name" href="{}">{}</a>'.format(
                    url_for(
                        'assess_bp.display_sub_criteria',
                         application_id=application_id,
                         sub_criteria_id=sub_criteria.id
                    ),
                    sub_criteria.name
                )
            },
            { "text": sub_criteria.score or "", "format": "numeric" } if g.access_controller.has_any_assessor_role else None,
            { "html": '<span class="{}">{}</span>'.format('govuk-tag--scored-criteria' if sub_criteria.status == 'NOT_STARTED' else '', 'Complete' if sub_criteria.status=='COMPLETED' else sub_criteria.status|all_caps_to_human),
                "format": "numeric" }
        ]) %}
    {% endfor %}

    {% set _ = rows.append([
        { "html": "<strong>Total criteria score</strong>" },
        { "text": "" },
        { "text": "{} of {}".format(criteria.total_criteria_score, criteria.total_criteria_score_possible), "format": "numeric" },
    ]) if g.access_controller.has_any_assessor_role %}

    <h3 class="{{ name_classes or '' }}">{{ criteria.name }}</h3>
    <p class="govuk-body govuk-!-margin-bottom-2">
        <strong>{{ (criteria.weighting * 100)|int }}%</strong> of overall score.
    </p>

    {{
        govukTable({
        "firstCellIsHeader":false,
        "head": [
            { "text": "Assessment sub criteria", "classes": "govuk-!-width-one-half"  },
            { "text": "Score out of 5", "format": "numeric" } if g.access_controller.has_any_assessor_role else None,
            { "text": "Status", "format": "numeric" }
        ],
        "rows": rows,
        "classes": "govuk-!-margin-bottom-6 govuk-table-no-bottom-border"
    }) }}

{% endmacro %}

assess/app/assess/templates/macros/criteria_element.jinja2
{%- from "govuk_frontend_jinja/components/table/macro.html" import govukTable -%}
{% macro criteria_element(criteria, name_classes, application_id) %}

    {% set rows = [] %}
    {% for sub_criteria in criteria.sub_criterias %}
        {% set _ = rows.append([
            {
                "html": '<a class="govuk-link" href="{}">{}</a>'.format(
                    url_for(
                        'assess_bp.display_sub_criteria',
                         application_id=application_id,
                         sub_criteria_id=sub_criteria.id
                    ),
                    sub_criteria.name
                )
            },
            { "text": sub_criteria.theme_count, "format": "numeric" },
            { "text": sub_criteria.score, "format": "numeric" },
            { "html": '<span class="govuk-tag--scored-criteria">{}</span>'.format(sub_criteria.status), "format": "numeric" }
        ]) %}
    {% endfor %}

    {% set _ = rows.append([
        { "html": "<strong>Total criteria score</strong>" },
        { "text": "" },
        { "text": "" },
        { "text": "{} of {}".format(criteria.total_criteria_score, criteria.total_criteria_score_possible), "format": "numeric" },
    ]) %}

    <h3 class="{{ name_classes or '' }}">{{ criteria.name }}</h3>
    <p class="govuk-body govuk-!-margin-bottom-2">
        <strong>{{ (criteria.weighting * 100)|int }}%</strong> of overall score.
    </p>

    {{ govukTable({
        "firstCellIsHeader":false,
        "head":[
            { "text": "Assessment sub criteria" },
            { "text": "Number of sections", "format": "numeric" },
            { "text": "Score", "format": "numeric" },
            { "text": "Status", "format": "numeric" }
        ],
        "rows": rows,
        "classes": "govuk-!-margin-bottom-6 govuk-table-no-bottom-border"
    }) }}

{% endmacro %}

assess/app/assess/templates/macros/flag_history.html
{%- from "govuk_frontend_jinja/components/table/macro.html" import govukTable -%}
{%- from "govuk_frontend_jinja/components/tabs/macro.html" import govukTabs -%}

{% macro display_flagged_sections(state, application_id, sections_to_flag) %}
    {% for sub_section_id in sections_to_flag %}
        {% set sub_section_data = state.get_section_from_sub_criteria_id(sub_section_id) %}
        {% if sub_section_data %}
            <p><a class="govuk-link govuk-link--no-visited-state" href="{{ url_for('assess_bp.display_sub_criteria',application_id=application_id ,sub_criteria_id=sub_section_id) }}" target="_blank">{{ sub_section_data["sub_section_name"] }}</a> ({{ sub_section_data["parent_section_name"] }}) (Opens in new tab) </p>
        {% else %}
            <p>{{ sub_section_id }}</p>
        {% endif %}
    {% endfor %}
{% endmacro %}

{% macro flag_table(state, application_id, flag_data, accounts_list) %}
    {% set items = [] %}
    {% for data in flag_data.updates %}
        {% set FlagDetails %}
            {% if data['status'].name=='RAISED' %}
                <p><strong>Reason</strong><br>{{ data['justification'] }}</p>
                <p><strong>Section(s) flagged</strong><br></p>
                {{ display_flagged_sections(state, application_id, flag_data['sections_to_flag']) }}
                <p><strong>Flag allocation</strong><br> <span class="flagged-tag"> {{ "Flagged for"+ data['allocation'] if data['allocation'] else "N/A" }}</span></p>
                <p><strong>Notification sent</strong><br>No</p>
            {% else %}
                {% if data['status'].name=='STOPPED' %}
                    <p><strong>Resolve flag action</strong><br>Stop assessment</p>
                {% elif data['status'].name=='ESCALATED' %}
                    <p><strong>Resolve flag action</strong><br>Flag escalated to {{ data['allocation'] }}</p>
                {% elif data['status'].name=='RESOLVED' %}
                    <p><strong>Resolve flag action</strong><br>Query resolved</p>
                {% endif %}
                <p><strong>Reason</strong><br>{{ data['justification'] }}</p>
            {% endif %}

        {% endset %}

        {% set username_date = '('+ accounts_list[data['user_id']]['full_name'] + ')<br>'+ data['date_created'] | utc_to_bst %}
        {% set CreatedBy = username_date if data['status'].name=='RAISED' else 'N/A' %}
        {% set ResolvedBy = username_date if data['status'].name!='RAISED' else 'N/A' %}

        {% set addItem = items.append([{'html': CreatedBy},
                                        {'text': FlagDetails},
                                        {'html': ResolvedBy},
                                        {'text': data['status'].name | capitalize}]) %}
    {% endfor %}

    <h2 class="govuk-heading-l">{{ "Flagged for "+ flag_data.latest_allocation if flag_data.latest_allocation else "Flagged" }}</h2>
    {{ govukTable({
    'head': [
        {'text': "Created by"},
        {'text': "Flag details"},
        {'text': "Resolved by"},
        {'text': "Flag status"}
    ],
    'rows': items
    })}}
{% endmacro %}

{% macro flag_tabs(state, application_id, flags_list, accounts_list) %}
    {% set TabsData %}
        {% set items = [] %}
        {% for flag_item in flags_list %}
            {% set addItem = items.append({
            'label': ("Flagged for " + flag_item.latest_allocation) if flag_item.latest_allocation else ("Flag " + (loop.index0 +1) | string),
            'id': "tab-" + (flag_item.latest_allocation if flag_item.latest_allocation else loop.index0 | string),
            'panel': {
                'html': flag_table(state, application_id, flag_item, accounts_list)}
            })%}
        {% endfor %}

        {{ govukTabs({
        'items': items
        }) }}
    {% endset %}

    <details class="govuk-details" data-module="govuk-details" open="">
        <summary class="govuk-details__summary">
        <span class="govuk-details__summary-text">
            Flag history
        </span>
        </summary><br><br>
        {{ TabsData }}
    </details>

{% endmacro %}

assess/app/assess/templates/macros/fund_dashboard_summary.html
{%- from "govuk_frontend_jinja/components/table/macro.html" import govukTable -%}

{% macro fund_summary(name, is_active_status, application_stats, assessments_href) %}
    <div class="govuk-!-padding-0 govuk-!-padding-right-2 govuk-!-padding-bottom-2 govuk-grid-column-one-third content-container">
        <h3 class="govuk-heading-s response-title">
            {{ name }}
        </h3>
        <div class="template-answer bg-white govuk-!-padding-bottom-5">

            <strong class="govuk-tag {% if not is_active_status %}govuk-tag--grey{% endif %} govuk-!-margin-bottom-2">
                {% if is_active_status %}
                    ASSESSMENT ACTIVE
                {% else %}
                    ASSESSMENT CLOSED
                {% endif %}
            </strong>

            {{ govukTable({
            "caption": "",
            "firstCellIsHeader": false,
            "rows": [
                [{'html': '<strong>Assessment closing date</strong>', 'classes': 'govuk-!-width-one-third'},
                 {'text': application_stats.date | datetime_format("%d %B %Y at %H:%M") }],
                [{'html': '<strong>Applications received</strong>'},
                 {'text': application_stats.total_received}],
                [{'html': '<strong>Assessments completed</strong>'},
                 {'text': application_stats.completed}],
                [{'html': '<strong>Assessments started</strong>'},
                 {'text': application_stats.started}],
                [{'html': '<strong>QA Complete</strong>'},
                 {'text': application_stats.qa_complete}],
                [{'html': '<strong>Stopped assessments</strong>'},
                 {'text': application_stats.stopped}],
            ],
            }) }}

            <a class="govuk-link" data-qa="dashboard_summary" href="{{ assessments_href }}">
                View all {% if is_active_status %}active{% else %}
                closed{% endif %} assessments
            </a>
        </div>
    </div>
{% endmacro %}

assess/app/assess/templates/macros/justification.html
{%- from 'govuk_frontend_jinja/components/textarea/macro.html' import govukTextarea -%}

{% macro justification(form, justification_error) %}

<div class="govuk-form-group comments {% if form.errors.get('justification') %}govuk-form-group--error{% endif %}" name="just-text-area" id="just-text-area">
    <h2 class="govuk-label-wrapper">
        <label for="justification" class="govuk-label govuk-label--m">Add rationale for this score</label>
    </h2>
    <div id="more-detail-hint" class="govuk-hint">
        Explain why you think this score is justified based on the assessment
        criteria
    </div>
    {% if form.errors.get("justification") %}
    <p id="justification-error" class="govuk-error-message">
        <span class="govuk-visually-hidden">Error:</span> Please provide rationale for this score
      </p>
    {% endif %}
    <textarea class="govuk-textarea" id="justification" name={{ form.justification.id }}
        rows="10" aria-describedby="more-detail-hint">{% if form.justification.data %}{{ form.justification.data }}{% endif %}</textarea>
</div>

{% endmacro %}

assess/app/assess/templates/macros/sub_criteria_navbar.html
{% macro navbar(application_id, sub_criteria, current_theme_id, is_score_page=False) %}
<nav class="assessment-navigation">
    <ul class="govuk-list">
        {% for theme in sub_criteria.themes %}
        {% set is_current_url = (current_theme_id == theme.id) and not is_score_page %}
        <li>
            {% if not is_current_url %}
            <a class="govuk-link govuk-link--no-visited-state" data-qa="sub_criteria_theme"
            href="{{ url_for('assess_bp.display_sub_criteria',application_id=application_id,sub_criteria_id=sub_criteria.id,theme_id=theme.id) }}">
            {% endif %}
            {{ theme.name }}
            {% if not is_current_url %}
            </a>
            {% endif %}
        </li>
        {% endfor %}
    </ul>

{% if g.access_controller.has_any_assessor_role and sub_criteria.is_scored %}
    <ul class="govuk-list">
        <li>
            {% if not is_score_page %}
            <a id="score-subcriteria-link" class="govuk-link govuk-link--no-visited-state" href="{{ url_for('assess_bp.score',application_id=application_id,sub_criteria_id=sub_criteria.id) }}">
            {% endif %}
            Score the subcriteria
            {% if not is_score_page %}
            </a>
            {% endif %}
        </li>
    </ul>
{% endif %}
</nav>

{% endmacro %}